[package]
name = "api-key"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4", "v7"] }
sha3 = "0.10"
data-encoding = "2"
rand = "0.8"
subtle = "2"
zeroize = { version = "1", features = ["derive"] }
thiserror = "2"
